### ISSUE TITLE
Invariant range filed lost min-max information in DataStore

### ISSUE THREAD

**Issue by NLGithubWP** [COOL-cohort/COOL#113]
Previously, each range filed had a min and max value in the DataField. Now, since we merge the invariant fields with userID, we lost those information.

**Comment by NLGithubWP** [comment]
Fixed in pr(https://github.com/COOL-cohort/COOL/pull/114)

**Comment by KimballCai** [comment]
considering that data chunk skip may not save much time, we did not store summary information (e.g., min and max values in the invariant range field, and all existence ids in the invariant set field) in each data chunk.

**Comment by KimballCai** [comment]
We have added the min and max values in each data chunk for the invariant range field, but these adjustments are disabled temporally.
