### ISSUE TITLE
Birth event not used for age selection

### ISSUE THREAD

**Issue by KimballCai** [COOL-cohort/COOL#119]
according to the current code logic, a user with only one record will never be classified into any cohort. Please fix it.

**Comment by Zrealshadow** [comment]
please write a unit test for this corner case

**Comment by hugy718** [comment]
I have looked into this problem and modified the Issue title to reflect the real problem.

## Problem

The Cohort processor only process records of a user after she is born. The corner case is that birth event is not considered for age selection. This resulted in discrepancies for users that do not have subsequent records at the age 0 yet their birth event passes cohort selection
