### ISSUE TITLE
Input cohort implementation

### ISSUE THREAD

**Issue by KimballCai** [COOL-cohort/COOL#133]
This system can save cohort results in a certain format, and we need to reload these cohort results to filter users when processing other cohort queries.

**Comment by NLGithubWP** [comment]
This is added in this PR https://github.com/COOL-cohort/COOL/pull/106

**Comment by hugy718** [comment]
`CohortAnalysis` implementation is wrong.

https://github.com/COOL-cohort/COOL/blob/07ce69b55db0b524ba88fa6e443bfccb8f99bb32/cool-core/src/main/java/com/nus/cool/functionality/CohortAnalysis.java#L64
 
It used `readQueryCohorts` that would load all cohorts written out. So basically all born users.

The processor also only tested that function.

https://github.com/COOL-cohort/COOL/blob/07ce69b55db0b524ba88fa6e443bfccb8f99bb32/cool-core/src/test/java/com/nus/cool/core/ProcessorTest.java#L75

Now, the all cohorts are written out by `persistCohort`, which is not necessary. I will restructure how persistence is done in #136  before tackling this one.

**Comment by hugy718** [comment]
solved by #139
