### ISSUE TITLE
Cube List Test fail during mvn clean package

### ISSUE THREAD

**Issue by IshantWankhede** [COOL-cohort/COOL#27]
Following test passed.
Csv data loader Test
Cube Reload Test
Cohort Selection Test
Cohort Analysis Test
Funnel Analysis Test
IceBerg Test
CohortProfilingTest Test

Below test build failed.

`======================== Cube List Test ========================
Applications: [sogamo, tpc-h-10g, health]
Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.245 sec <<< FAILURE!
CohortSelectionTest(com.nus.cool.core.model.CoolModelTest)  Time elapsed: 0.029 sec  <<< FAILURE!
java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:699)
	at java.base/java.nio.DirectShortBufferU.get(DirectShortBufferU.java:321)
	at com.nus.cool.core.io.storevector.ZInt16Store.next(ZInt16Store.java:67)
	at com.nus.cool.core.io.storevector.FoRInputVector.next(FoRInputVector.java:57)
	at com.nus.cool.core.cohort.TimeUtils.getDateFromOffset(TimeUtils.java:53)
	at com.nus.cool.core.cohort.ExtendedCohortSelection.getUserBirthTime(ExtendedCohortSelection.java	at com.nus.cool.core.cohort.ExtendedCohortSelection.getUserBirthTime(ExtendedCohortSelection.java	at com.nus.cool.core.cohort.ExtendedCohortSelection.getUserBirthTime(ExtendedCohortSelection.java:427)
	at com.nus.cool.core.cohort.ExtendedCohortSelection.selectUser(ExtendedCohortSelection.java:511)
	at com.nus.cool.core.cohort.CohortUserSection.process(CohortUserSection.java:150)
	at com.nus.cool.model.CoolCohortEngine.selectCohortUsers(CoolCohortEngine.java:63)
	at com.nus.cool.core.model.CoolModelTest.CohortSelectionTest(CoolModelTest.java:96)

Results :

Failed tests:   CohortSelectionTest(com.nus.cool.core.model.CoolModelTest)

Tests run: 13, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for cool 0.1-SNAPSHOT:
[INFO] 
[INFO] cool ............................................... SUCCESS [02:26 min]
[INFO] cool-core .......................................... FAILURE [02:30 min]
[INFO] cool-extensions .................................... SKIPPED
[INFO] parquet-extensions ................................. SKIPPED
[INFO] hdfs-extensions .................................... SKIPPED
[INFO] arrow-extensions ................................... SKIPPED
[INFO] avro-extensions .................................... SKIPPED
[INFO] cool-queryserver ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:57 min
[INFO] Finished at: 2022-04-18T15:58:23+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project cool-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/i0w00to/apache/COOL/cool-core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cool-core
`

**Comment by KimballCai** [comment]
Thanks for your interest and your participation.

The problem is in the CohortSelectionTest test function, not the Cube List Test.

It is because there is an error in the development of  PR #25. 

Index out of boundary in the com.nus.cool.core.cohort.ExtendedCohortSelection.getUserBirthTime(ExtendedCohortSelection.java:427)

**Comment by KimballCai** [comment]
Fixed

**Comment by IshantWankhede** [comment]
mvn build success after pulling changes from [[d5032ec]]((https://github.com/COOL-cohort/COOL/commit/d5032ec2cd051b4b85b2f58ae7bbf278cd9e4574))
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for cool 0.1-SNAPSHOT:
[INFO] 
[INFO] cool ............................................... SUCCESS [  1.027 s]
[INFO] cool-core .......................................... SUCCESS [ 20.363 s]
[INFO] cool-extensions .................................... SUCCESS [  0.610 s]
[INFO] parquet-extensions ................................. SUCCESS [03:16 min]
[INFO] hdfs-extensions .................................... SUCCESS [ 57.733 s]
[INFO] arrow-extensions ................................... SUCCESS [ 34.259 s]
[INFO] avro-extensions .................................... SUCCESS [ 20.157 s]
[INFO] cool-queryserver ................................... SUCCESS [01:38 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:09 min
[INFO] Finished at: 2022-04-19T11:20:45+05:30
[INFO] ------------------------------------------------------------------------

```
