### ISSUE TITLE
BUILD FAILURE: test failures

### ISSUE THREAD

**Issue by qlinsey** [COOL-cohort/COOL#28]
ENV: On MacBook Pro 11.6.5 
Steps on Terminal: 
1. git clone https://github.com/COOL-cohort/COOL.git
2. mvn clean package
Output: 
[INFO] [------------------------------------------------------------------------]
[INFO] Reactor Summary for cool 0.1-SNAPSHOT:
[INFO] 
[INFO] cool ............................................... SUCCESS [ 13.606 s]
[INFO] cool-core .......................................... FAILURE [ 17.090 s]
[INFO] cool-extensions .................................... SKIPPED
[INFO] parquet-extensions ................................. SKIPPED
[INFO] hdfs-extensions .................................... SKIPPED
[INFO] arrow-extensions ................................... SKIPPED
[INFO] avro-extensions .................................... SKIPPED
[INFO] cool-queryserver ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.792 s
[INFO] Finished at: 2022-04-18T20:52:21-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project cool-core: There are test failures.
From testng-results.xml (cannot attach due to file type), 

<test-method signature="CohortSelectionTest()[pri:2, instance:com.nus.cool.core.model.CoolModelTest@69a3d1d]" started-at="2022-04-18T20:52:20 PDT" name="CohortSelectionTest" finished-at="2022-04-18T20:52:20 PDT" duration-ms="37" status="FAIL">
<exception class="java.nio.BufferUnderflowException">
<full-stacktrace>
<![CDATA[ java.nio.BufferUnderflowException at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:699) at java.base/java.nio.DirectShortBufferU.get(DirectShortBufferU.java:321) at com.nus.cool.core.io.storevector.ZInt16Store.next(ZInt16Store.java:67) at com.nus.cool.core.io.storevector.FoRInputVector.next(FoRInputVector.java:57) at com.nus.cool.core.cohort.TimeUtils.getDateFromOffset(TimeUtils.java:53) at com.nus.cool.core.cohort.ExtendedCohortSelection.getUserBirthTime(ExtendedCohortSelection.java:427) at com.nus.cool.core.cohort.ExtendedCohortSelection.selectUser(ExtendedCohortSelection.java:511) at com.nus.cool.core.cohort.CohortUserSection.process(CohortUserSection.java:150) at com.nus.cool.model.CoolCohortEngine.selectCohortUsers(CoolCohortEngine.java:63) at com.nus.cool.core.model.CoolModelTest.CohortSelectionTest(CoolModelTest.java:96) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:577) at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) at org.testng.TestRunner.privateRun(TestRunner.java:766) at org.testng.TestRunner.run(TestRunner.java:587) at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) at org.testng.SuiteRunner.run(SuiteRunner.java:286) at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) at org.testng.TestNG.runSuites(TestNG.java:1039) at org.testng.TestNG.run(TestNG.java:1007) at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77) at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159) at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99) at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:577) at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) ]]>
</full-stacktrace>
</exception>

<reporter-output> </reporter-output>
</test-method>

**Comment by KimballCai** [comment]
Hi qlinsey,

It runs smoothly on several machines.

Can you provide more details about the error? or Are you using the latest version of the COOL?

**Comment by qlinsey** [comment]
Hi, 
After git pull and updated to latest, it works. I will close it.
