### ISSUE TITLE
IcebergQueryTest implicit dependencies on CsvLoaderTest

### ISSUE THREAD

**Issue by hugy718** [COOL-cohort/COOL#82]
EcommerceDataSetSQL1 test under IcebergQueryTest assumes that CsvLoaderTest to have loaded ecommerce data loaded in the cube repo. Yet this dependency unlike CohortSelectionTest/CohortAnalysisTest is not specified.

**Comment by hugy718** [comment]
Maybe its better to reorganize the `iceberg/query` folder? Other functionality tests on loaded datasets are placed under `functionality` folder. @NLGithubWP

**Comment by KimballCai** [comment]
Need to modify the structure of these unit tests.

**Comment by hugy718** [comment]
Now iceberg tests has been temporarily removed from dev. It will be fixed once porting is complete #138
