### ISSUE TITLE
code formating with checkstyle

### ISSUE THREAD

**Issue by hugy718** [COOL-cohort/COOL#93]
Use checkstyle to enforce a consistent code formatting.
*  inconsistent code formatting between legacy and new codes, and between Intellij users and vscode users.
* Developers are enticed to change formatting, for example indentations, to remove IDE warning or simply because of different coding habits. But, the bad thing is that, during code review, formatting changes confuse the Github diff highlighter and obscure what needs to be reviewed.
* So my plan is:
  * We provide an checkstyle xml file (I intend to use the [google_check.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) in this repo, so all developers uses one consistent settings to format their codes.
  * One time effort to remove all checkstyle detected problems on formatting, naming, etc. And all of us uses that as the new base of development and fix all checkstyle warning before submitting new PRs.

**Comment by Zrealshadow** [comment]
I use the `eclipse-formatter.xml` which is the default formatter in vscode.
If we set a unified formatter file, we can create a github cli to check the new PR's code format.

I agree with that we should fix all warning before submitting new PR.
